branch-defaults:
  master:
    environment: mediabrothers
    group_suffix: null
global:
  application_name: mediabrothers
  default_ec2_keyname: mediabrosv2
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
